{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "coordination-engine.fullname" . }}-monitoring-view
  labels:
    {{- include "coordination-engine.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: {{ include "coordination-engine.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
